### ISSUE TITLE
Build not finding Maven

### ISSUE THREAD

**Issue by mcpierce** [skx/github-action-build#3]
I'm trying to use this action to build our Maven-based project, but the build is failing with the error:

```.github/build: line 1: mvn: command not found```

How does one configure this action to use an image that contains the following build prerequisites:
1. Maven
1. Java 1.8
1. NPM

**Comment by skx** [comment]
I'd probably suggest adding:

      apt-get update --quiet
      apt-get --assume-yes install  maven

To the top of your script, which would install the package.
